package oam

import (
	"fmt"
	"strings"

	"sigs.k8s.io/controller-runtime/pkg/client"

	"github.com/go-kure/launcher/pkg/errors"
)

// GeneratedDocument is one authored document's generated output, as a caller that
// transforms several documents holds it: the document's identity and every object
// generated from its Transform result, including any a layout walk adds.
type GeneratedDocument struct {
	Namespace string // authored metadata.namespace
	Name      string // authored metadata.name
	Kind      string // authored kind, e.g. "WebApplication"
	Objects   []*client.Object
}

func (d GeneratedDocument) String() string {
	return fmt.Sprintf("%s %q", d.Kind, qualifiedName(d.Namespace, d.Name))
}

func qualifiedName(namespace, name string) string {
	if namespace == "" {
		return name
	}
	return namespace + "/" + name
}

// objectIdentity is what makes two generated objects the same Kubernetes object:
// API group, kind, namespace and name. The version is excluded, since one object
// served under two versions is still one object.
type objectIdentity struct {
	group, kind, namespace, name string
}

func (o objectIdentity) String() string {
	kind := o.kind
	if o.group != "" {
		kind += "." + o.group
	}
	return fmt.Sprintf("%s %q", kind, qualifiedName(o.namespace, o.name))
}

// CheckCrossDocumentCollisions reports every generated object that more than one
// authored document produces (D2). Transform runs each document with its own
// NameAllocator, so a name an in-transform rule generates is never compared across
// documents: two same-namespace documents whose rules both emit a shared element
// through EmitOrAdopt each transform cleanly. A caller that transforms several
// documents passes every document's generated objects here to catch that
// collision, and any other two documents generating the same object: two
// same-named authored components in one namespace, or one cluster-scoped object
// generated from documents in different namespaces.
//
// Objects are keyed by API group, kind, namespace and name, as generated: an
// object's namespace is read from the object, never defaulted from its document,
// so a namespaced object must carry its namespace and a cluster-scoped one none.
// An object with no kind cannot be keyed and is an error; a nil entry is skipped.
// An object repeated within one document is not reported, since
// NameAllocator already guards one document's generated names. Listing the same
// document twice is an error.
func CheckCrossDocumentCollisions(docs []GeneratedDocument) error {
	type docKey struct{ namespace, kind, name string }
	seenDocs := make(map[docKey]bool, len(docs))
	owner := map[objectIdentity]int{}
	var collisions []string
	for i, doc := range docs {
		dk := docKey{doc.Namespace, doc.Kind, doc.Name}
		if seenDocs[dk] {
			return errors.Errorf("generated-object collision check: %s is listed more than once", doc)
		}
		seenDocs[dk] = true
		for _, p := range doc.Objects {
			if p == nil || *p == nil {
				continue
			}
			obj := *p
			gvk := obj.GetObjectKind().GroupVersionKind()
			if gvk.Kind == "" {
				return errors.Errorf("generated-object collision check: %s: object %q has no kind; set its apiVersion and kind so it can be compared",
					doc, qualifiedName(obj.GetNamespace(), obj.GetName()))
			}
			id := objectIdentity{group: gvk.Group, kind: gvk.Kind, namespace: obj.GetNamespace(), name: obj.GetName()}
			first, ok := owner[id]
			if !ok {
				owner[id] = i
				continue
			}
			if first != i {
				collisions = append(collisions, fmt.Sprintf("%s is generated by both %s and %s", id, docs[first], doc))
			}
		}
	}
	switch len(collisions) {
	case 0:
		return nil
	case 1:
		return errors.Errorf("generated-object collision: %s", collisions[0])
	default:
		return errors.Errorf("generated-object collision: %d generated objects are each produced by more than one document:\n  %s",
			len(collisions), strings.Join(collisions, "\n  "))
	}
}
