package oam

import (
	"encoding/json"
	"strings"
	"testing"

	kio "github.com/go-kure/kure/pkg/io"
	"github.com/go-kure/kure/pkg/stack"
	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"sigs.k8s.io/controller-runtime/pkg/client"

	"github.com/go-kure/launcher/pkg/errors"
)

func generatedApp(name, component string, objects ...*client.Object) GeneratedApplication {
	return GeneratedApplication{Name: name, Component: component, Objects: objects}
}

func TestCheckInDocumentCollisions(t *testing.T) {
	deployment := func(apiVersion, name string) *client.Object {
		return collisionObject(&appsv1.Deployment{
			TypeMeta:   metav1.TypeMeta{APIVersion: apiVersion, Kind: "Deployment"},
			ObjectMeta: metav1.ObjectMeta{Namespace: "shop", Name: name},
		})
	}
	secret := func(name string) *client.Object {
		return collisionObject(&corev1.Secret{
			TypeMeta:   metav1.TypeMeta{APIVersion: "v1", Kind: "Secret"},
			ObjectMeta: metav1.ObjectMeta{Namespace: "shop", Name: name},
		})
	}
	cases := []struct {
		name string
		apps []GeneratedApplication
		// want is the whole error message; "" means accepted.
		want string
	}{
		{
			name: "a trait sub-application and a component",
			apps: []GeneratedApplication{
				generatedApp("web", "web", configMap("shop", "web")),
				generatedApp("extra", "extra", configMap("shop", "shared")),
				generatedApp("shared", "web", configMap("shop", "shared")),
			},
			want: `generated-object collision: ConfigMap "shop/shared" is generated by both component "extra" and sub-application "shared" of component "web"; rename one so that each object has one producer`,
		},
		{
			name: "a component with no component name is named by its application",
			apps: []GeneratedApplication{
				generatedApp("web", "", configMap("shop", "shared")),
				generatedApp("api", "api", configMap("shop", "shared")),
			},
			want: `generated-object collision: ConfigMap "shop/shared" is generated by both component "web" and component "api"; rename one so that each object has one producer`,
		},
		{
			name: "three producers of one object are named on one line",
			apps: []GeneratedApplication{
				generatedApp("a", "a", configMap("shop", "shared")),
				generatedApp("b", "b", configMap("shop", "shared")),
				generatedApp("c", "c", configMap("shop", "shared")),
			},
			want: `generated-object collision: ConfigMap "shop/shared" is generated by component "a", component "b" and component "c"; rename one so that each object has one producer`,
		},
		{
			name: "several colliding objects are each reported once, in generation order",
			apps: []GeneratedApplication{
				generatedApp("a", "a", configMap("shop", "one"), configMap("shop", "two")),
				generatedApp("b", "b", configMap("shop", "two"), configMap("shop", "one")),
				generatedApp("c", "c", configMap("shop", "one")),
			},
			want: "generated-object collision: 2 generated objects are each produced by more than one application; rename one producer of each:\n" +
				`  ConfigMap "shop/two" is generated by both component "a" and component "b"` + "\n" +
				`  ConfigMap "shop/one" is generated by component "a", component "b" and component "c"`,
		},
		{
			name: "another version of one group and kind is the same object",
			apps: []GeneratedApplication{
				generatedApp("a", "a", deployment("apps/v1", "web")),
				generatedApp("b", "b", deployment("apps/v1beta2", "web")),
			},
			want: `generated-object collision: Deployment.apps "shop/web" is generated by both component "a" and component "b"; rename one so that each object has one producer`,
		},
		{
			name: "an object with no kind is refused",
			apps: []GeneratedApplication{
				generatedApp("settings", "web", collisionObject(&corev1.ConfigMap{ObjectMeta: metav1.ObjectMeta{Namespace: "shop", Name: "settings"}})),
			},
			want: `generated-object collision check: sub-application "settings" of component "web": object "shop/settings" has no kind; set its apiVersion and kind so it can be compared`,
		},
		{
			name: "one application generating an object twice is not reported",
			apps: []GeneratedApplication{
				generatedApp("a", "a", configMap("shop", "shared"), configMap("shop", "shared")),
				generatedApp("b", "b", configMap("shop", "other")),
			},
		},
		{
			name: "the same name in another namespace, kind or group is another object",
			apps: []GeneratedApplication{
				generatedApp("a", "a", configMap("shop", "shared")),
				generatedApp("b", "b", configMap("cart", "shared"), secret("shared"), deployment("apps/v1", "shared")),
				generatedApp("c", "c", collisionObject(&appsv1.Deployment{
					TypeMeta:   metav1.TypeMeta{APIVersion: "example.com/v1", Kind: "Deployment"},
					ObjectMeta: metav1.ObjectMeta{Namespace: "shop", Name: "shared"},
				})),
			},
		},
		{
			name: "nil entries and nil objects are skipped",
			apps: []GeneratedApplication{
				generatedApp("a", "a", nil, new(client.Object), collisionObject((*corev1.ConfigMap)(nil)), configMap("shop", "a")),
				generatedApp("b", "b", nil, new(client.Object), collisionObject((*corev1.ConfigMap)(nil)), configMap("shop", "b")),
			},
		},
		{name: "no applications"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			err := CheckInDocumentCollisions(tc.apps)
			if tc.want == "" {
				if err != nil {
					t.Fatalf("unexpected error: %v", err)
				}
				return
			}
			if err == nil || err.Error() != tc.want {
				t.Fatalf("error = %v\nwant %s", err, tc.want)
			}
		})
	}
}

// countingConfig generates one ConfigMap, counting its Generate calls, and names a
// component when component is set.
type countingConfig struct {
	name, namespace, component string
	labels                     map[string]string
	calls                      *int
}

func (c *countingConfig) Generate(*stack.Application) ([]*client.Object, error) {
	*c.calls++
	cm := configMap(c.namespace, c.name)
	(*cm).SetLabels(c.labels)
	return []*client.Object{cm}, nil
}

type componentNamedCountingConfig struct{ *countingConfig }

func (c componentNamedCountingConfig) ComponentName() string { return c.component }

// generationCluster builds a cluster of an umbrella root bundle with two labelled
// leaf children, and a child node with a leaf bundle of its own; every config
// counts its generations in calls.
func generationCluster(calls map[string]*int) *stack.Cluster {
	app := func(name, component string, labels map[string]string) *stack.Application {
		n := new(int)
		calls[name] = n
		cfg := &countingConfig{name: name, namespace: "shop", component: component, labels: labels, calls: n}
		if component != "" {
			return stack.NewApplication(name, "shop", componentNamedCountingConfig{cfg})
		}
		return stack.NewApplication(name, "shop", cfg)
	}
	infra := &stack.Bundle{
		Name:         "shop-infra",
		Labels:       map[string]string{"tier": "infra", "owner": "bundle"},
		Annotations:  map[string]string{"note": "infra"},
		Applications: []*stack.Application{app("agent", "", nil), app("settings", "agent", map[string]string{"owner": "app"})},
	}
	apps := &stack.Bundle{
		Name:         "shop-apps",
		Applications: []*stack.Application{app("web", "", nil)},
	}
	root := &stack.Bundle{Name: "shop", Children: []*stack.Bundle{infra, apps}}
	child := &stack.Node{Name: "db", Bundle: &stack.Bundle{Name: "db", Applications: []*stack.Application{app("db", "", nil)}}}
	return &stack.Cluster{Name: "shop", Node: &stack.Node{Name: "shop", Bundle: root, Children: []*stack.Node{child}}}
}

// TestGenerateApplications pins that GenerateApplications generates each
// application once, attributes it to its component, and returns the objects kure's
// own leaf Bundle.Generate returns, in the same order, bundle labels and
// annotations included.
func TestGenerateApplications(t *testing.T) {
	calls := map[string]*int{}
	apps, err := GenerateApplications(generationCluster(calls))
	if err != nil {
		t.Fatalf("GenerateApplications: %v", err)
	}
	var got []string
	for _, a := range apps {
		got = append(got, a.String())
	}
	want := []string{`component "agent"`, `sub-application "settings" of component "agent"`, `component "web"`, `component "db"`}
	if strings.Join(got, "; ") != strings.Join(want, "; ") {
		t.Errorf("applications = %q, want %q", got, want)
	}
	for name, n := range calls {
		if *n != 1 {
			t.Errorf("application %q generated %d times, want 1", name, *n)
		}
	}

	twin := generationCluster(map[string]*int{})
	var kure []*client.Object
	for _, b := range []*stack.Bundle{twin.Node.Bundle.Children[0], twin.Node.Bundle.Children[1], twin.Node.Children[0].Bundle} {
		objs, err := b.Generate()
		if err != nil {
			t.Fatalf("kure Bundle.Generate %q: %v", b.Name, err)
		}
		kure = append(kure, objs...)
	}
	var ours []*client.Object
	for _, a := range apps {
		ours = append(ours, a.Objects...)
	}
	gotYAML, err := kio.EncodeObjectsToYAML(ours)
	if err != nil {
		t.Fatalf("encoding: %v", err)
	}
	wantYAML, err := kio.EncodeObjectsToYAML(kure)
	if err != nil {
		t.Fatalf("encoding: %v", err)
	}
	if string(gotYAML) != string(wantYAML) {
		t.Errorf("objects differ from kure's Bundle.Generate:\n--- got\n%s\n--- want\n%s", gotYAML, wantYAML)
	}
	if !strings.Contains(string(gotYAML), "owner: app") || !strings.Contains(string(gotYAML), "note: infra") {
		t.Errorf("bundle labels or annotations not merged as kure merges them:\n%s", gotYAML)
	}
}

type failingConfig struct{ err error }

func (c failingConfig) Generate(*stack.Application) ([]*client.Object, error) { return nil, c.err }

func TestGenerateApplications_ReturnsGenerateErrorUnchanged(t *testing.T) {
	want := errors.New("chart render failed")
	cluster := &stack.Cluster{Node: &stack.Node{Bundle: &stack.Bundle{Applications: []*stack.Application{
		stack.NewApplication("web", "shop", failingConfig{err: want}),
	}}}}
	apps, err := GenerateApplications(cluster)
	if !errors.Is(err, want) || err.Error() != want.Error() {
		t.Fatalf("error = %v, want %v unchanged", err, want)
	}
	if apps != nil {
		t.Errorf("applications = %v, want none", apps)
	}
	if apps, err := GenerateApplications(nil); apps != nil || err != nil {
		t.Errorf("GenerateApplications(nil) = %v, %v; want nothing", apps, err)
	}
}

// configMapPropertyHandler is a component of type typ generating one ConfigMap,
// named by its "configMap" property, else after the component.
type configMapPropertyHandler struct{ typ string }

func (h *configMapPropertyHandler) CanHandle(t string) bool { return t == h.typ }

func (h *configMapPropertyHandler) ToApplicationConfig(c *Component, namespace string) (stack.ApplicationConfig, error) {
	name := c.Name
	if n, ok := c.Properties["configMap"].(string); ok {
		name = n
	}
	return &namedConfigMapConfig{name: name, namespace: namespace}, nil
}

// settingsTraitHandler adds a sub-application generating a ConfigMap named by the
// trait's "name" property, as the builtin configmap trait does.
type settingsTraitHandler struct{}

func (settingsTraitHandler) CanHandle(t string) bool { return t == "settings" }

func (settingsTraitHandler) Apply(trait *Trait, app *stack.Application, bundle *stack.Bundle) error {
	name, _ := trait.Properties["name"].(string)
	bundle.Applications = append(bundle.Applications,
		stack.NewApplication(name, app.Namespace, &settingsConfig{namedConfigMapConfig{name: name, namespace: app.Namespace}, app.Name}))
	return nil
}

type settingsConfig struct {
	namedConfigMapConfig
	component string
}

func (c *settingsConfig) ComponentName() string { return c.component }

// siblingRule lowers a "grouped" component into a same-name sibling group of a
// webservice and a daemonset, generating ConfigMaps <name>-a and <name>-b.
type siblingRule struct{}

func (siblingRule) ComponentType() string { return "grouped" }

func (siblingRule) LowerComponent(comp *Component, _ LoweringContext) (LoweringResult, error) {
	return LoweringResult{Components: []Component{
		{Name: comp.Name, Type: "webservice", Properties: map[string]any{"configMap": comp.Name + "-a"}},
		{Name: comp.Name, Type: "statefulset", Properties: map[string]any{"configMap": comp.Name + "-b"}},
	}}, nil
}

func inDocumentTransformer() *Transformer {
	tr := NewTransformer(map[string]ComponentHandler{
		"webservice":  &configMapPropertyHandler{typ: "webservice"},
		"daemonset":   &configMapPropertyHandler{typ: "daemonset"},
		"statefulset": &configMapPropertyHandler{typ: "statefulset"},
		"worker":      &configMapPropertyHandler{typ: "worker"},
	}, map[string]TraitHandler{"settings": settingsTraitHandler{}})
	tr.RegisterComponentLowering(siblingRule{})
	tr.RegisterComponentLowering(imageSourceRule{})
	return tr
}

// generateAndCheck generates cluster and runs the in-document check over it.
func generateAndCheck(t *testing.T, cluster *stack.Cluster) error {
	t.Helper()
	apps, err := GenerateApplications(cluster)
	if err != nil {
		t.Fatalf("GenerateApplications: %v", err)
	}
	return CheckInDocumentCollisions(apps)
}

// TestCheckInDocumentCollisions_AfterTransform is go-kure/launcher#646: two
// producers in one document generating one object pass Transform, on each of its
// three cluster shapes, and the check over the generated document refuses them.
func TestCheckInDocumentCollisions_AfterTransform(t *testing.T) {
	settings := func(name string) []Trait {
		return []Trait{{Type: "settings", Properties: map[string]any{"name": name}}}
	}
	component := func(name, typ, configMap string, traits []Trait) Component {
		c := Component{Name: name, Type: typ, Traits: traits, Properties: map[string]any{}}
		if configMap != "" {
			c.Properties["configMap"] = configMap
		}
		return c
	}
	shapes := []struct {
		name string
		// second is the second component's type: webservice keeps one tier
		// (flat), daemonset adds the infra tier (hierarchical).
		second     string
		dependency bool
	}{
		{name: "flat", second: "webservice"},
		{name: "hierarchical", second: "daemonset"},
		{name: "dependency-aware", second: "webservice", dependency: true},
	}
	producers := []struct {
		name       string
		web, other Component
		want       []string // "" means accepted
	}{
		{
			name:  "trait and trait",
			web:   component("web", "webservice", "", settings("settings")),
			other: component("other", "", "", settings("settings")),
			want:  []string{`ConfigMap "test/settings" is generated by both`, `sub-application "settings" of component "web"`, `sub-application "settings" of component "other"`},
		},
		{
			name:  "trait and component",
			web:   component("web", "webservice", "", settings("shared")),
			other: component("other", "", "shared", nil),
			want:  []string{`ConfigMap "test/shared" is generated by both`, `sub-application "shared" of component "web"`, `component "other"`},
		},
		{
			name:  "component and component",
			web:   component("web", "webservice", "shared", nil),
			other: component("other", "", "shared", nil),
			want:  []string{`ConfigMap "test/shared" is generated by both`, `component "web"`, `component "other"`},
		},
		{
			name:  "distinct objects",
			web:   component("web", "webservice", "", settings("web-settings")),
			other: component("other", "", "", settings("other-settings")),
		},
	}
	for _, shape := range shapes {
		for _, p := range producers {
			t.Run(shape.name+", "+p.name, func(t *testing.T) {
				tr := inDocumentTransformer()
				other := p.other
				other.Type = shape.second
				app := makeApp("shop", p.web, other)
				app.APIVersion, app.Kind = SupportedAPIVersion, terminalDocumentKind
				if shape.dependency {
					tr.RegisterPolicy("dependency", &depWritingPolicyHandler{from: "web", to: "other"})
					app.Spec.Policies = []ApplicationPolicy{{Name: "order", Type: "dependency"}}
				}
				cluster, _, err := tr.TransformWithPolicy(app, TransformContext{})
				if err != nil {
					t.Fatalf("TransformWithPolicy: %v", err)
				}
				err = generateAndCheck(t, cluster)
				if len(p.want) == 0 {
					if err != nil {
						t.Fatalf("unexpected error: %v", err)
					}
					return
				}
				if err == nil {
					t.Fatal("two producers of one object were not reported")
				}
				for _, w := range p.want {
					if !strings.Contains(err.Error(), w) {
						t.Errorf("error %q does not contain %q", err, w)
					}
				}
			})
		}
	}
}

// TestCheckInDocumentCollisions_SiblingGroup pins that a sibling group is one
// producer, named by its component, and that another component generating a
// member's object is refused.
func TestCheckInDocumentCollisions_SiblingGroup(t *testing.T) {
	tr := inDocumentTransformer()
	app := makeApp("shop",
		Component{Name: "web", Type: "grouped"},
		Component{Name: "other", Type: "webservice", Properties: map[string]any{"configMap": "web-b"}},
	)
	app.APIVersion, app.Kind = SupportedAPIVersion, terminalDocumentKind
	cluster, err := tr.Transform(app, TransformContext{})
	if err != nil {
		t.Fatalf("Transform: %v", err)
	}
	err = generateAndCheck(t, cluster)
	want := `generated-object collision: ConfigMap "test/web-b" is generated by both component "web" and component "other"; rename one so that each object has one producer`
	if err == nil || err.Error() != want {
		t.Fatalf("error = %v\nwant %s", err, want)
	}
}

// TestCheckInDocumentCollisions_EmitOrAdoptSharedSource is the near miss: two
// components sharing one source through EmitOrAdopt emit it once, so the document,
// whether transformed directly or lowered from a raw document first, has one
// producer of it.
func TestCheckInDocumentCollisions_EmitOrAdoptSharedSource(t *testing.T) {
	t.Run("Transform", func(t *testing.T) {
		tr := inDocumentTransformer()
		app := makeApp("shop",
			Component{Name: "a", Type: "image-source-user", Properties: map[string]any{"image": "nginx:1"}},
			Component{Name: "b", Type: "image-source-user", Properties: map[string]any{"image": "nginx:1"}},
		)
		app.APIVersion, app.Kind = SupportedAPIVersion, terminalDocumentKind
		cluster, err := tr.Transform(app, TransformContext{})
		if err != nil {
			t.Fatalf("Transform: %v", err)
		}
		if err := generateAndCheck(t, cluster); err != nil {
			t.Fatalf("a source shared through EmitOrAdopt was refused: %v", err)
		}
	})
	t.Run("LowerRaws", func(t *testing.T) {
		tr := inDocumentTransformer()
		tr.RegisterRawDocumentLowering(testRawRule{kind: "WebApplication", compType: "image-source-user"})
		out, err := tr.LowerRaws([]json.RawMessage{rawWebApplication("shop")}, TransformContext{})
		if err != nil {
			t.Fatalf("LowerRaws: %v", err)
		}
		for _, raw := range out {
			app := parseLoweredOutput(t, tr, raw)
			cluster, err := tr.Transform(app, TransformContext{Namespace: "prod"})
			if err != nil {
				t.Fatalf("Transform %q: %v", app.Metadata.Name, err)
			}
			apps, err := GenerateApplications(cluster)
			if err != nil {
				t.Fatalf("GenerateApplications: %v", err)
			}
			if len(apps) == 0 {
				t.Fatal("generated no applications")
			}
			if err := CheckInDocumentCollisions(apps); err != nil {
				t.Fatalf("a lowered document was refused: %v", err)
			}
		}
	})
}
