apiVersion: launcher.gokure.dev/v1alpha1
kind: Application
metadata:
  name: my-third-party
spec:
  components:
  - name: redis
    type: helmchart
    properties:
      chart: redis
      version: "18.6.1"
      source:
        url: https://charts.bitnami.com/bitnami
      values:
        auth:
          enabled: false
        master:
          persistence:
            enabled: true
            size: "8Gi"
        replica:
          replicaCount: 1
