package traits

import (
	"github.com/go-kure/kure/pkg/stack"
	"github.com/go-kure/kure/pkg/stack/layout"
	"sigs.k8s.io/controller-runtime/pkg/client"

	"github.com/go-kure/launcher/pkg/oam"
)

// Flux kustomize-controller's force-apply annotation. kustomize-controller
// uses exactly this key and value as its apply ForceSelector: an object
// carrying it is deleted and recreated when a server-side apply fails on an
// immutable field. kure's stack package defines the prune annotation but not
// this one.
const (
	annotationFluxForceKey     = "kustomize.toolkit.fluxcd.io/force"
	annotationFluxForceEnabled = "enabled"
)

// ForceReplaceHandler handles OAM force-replace traits.
//
// When applied, all Kubernetes resources generated for the component are
// annotated with kustomize.toolkit.fluxcd.io/force: enabled, so Flux replaces
// (deletes and recreates) an object whose update would otherwise fail on an
// immutable field — a Job's pod template being the case the trait exists for.
// Replacing a Job re-runs it, stopping any run in progress. The trait takes no
// properties and is opt-in: without it launcher does not add the annotation.
type ForceReplaceHandler struct{}

// CanHandle returns true for the "force-replace" trait type.
func (h *ForceReplaceHandler) CanHandle(traitType string) bool {
	return traitType == "force-replace"
}

// PropertySchema declares the force-replace trait's properties. It accepts no
// user-facing properties (it is a pure decorator), so the schema is empty.
func (h *ForceReplaceHandler) PropertySchema() map[string]oam.PropertySchema {
	return map[string]oam.PropertySchema{}
}

// Apply wraps app.Config with a forceReplaceConfig decorator so that every
// resource generated by this application receives the force annotation.
//
// Coverage and scope are prune-protection's (see PruneProtectionHandler.Apply):
// the component's own Generate output plus, for a layout.LayoutAugmenter
// config, every resource on its per-app layout after AugmentLayout ran, and,
// through DecoratesSubApplications, the sub-applications the component's other
// traits append to the bundle.
//
// The annotation is set after the inner Generate returns, so it survives a
// component that resets its objects' annotations while building them (the job
// component's createJob does).
func (h *ForceReplaceHandler) Apply(_ *oam.Trait, app *stack.Application, _ *stack.Bundle) error {
	app.Config = wrapIfAugmenter(
		&forceReplaceConfig{decoratorBase: decoratorBase{Inner: app.Config}},
		app.Config)
	return nil
}

// DecoratesSubApplications reports that the trait also covers the component's
// trait sub-applications (oam.SubApplicationDecorator).
func (h *ForceReplaceHandler) DecoratesSubApplications() bool { return true }

var _ oam.SubApplicationDecorator = (*ForceReplaceHandler)(nil)

// forceReplaceConfig wraps an ApplicationConfig and injects
// annotationFluxForceKey = annotationFluxForceEnabled into every resource
// returned by the wrapped config's Generate method, and into every resource on
// the layout its AugmentLayout populates (postAugmentLayout).
type forceReplaceConfig struct {
	decoratorBase
}

var _ layoutPostAugmenter = (*forceReplaceConfig)(nil)

func (f *forceReplaceConfig) Generate(app *stack.Application) ([]*client.Object, error) {
	resources, err := f.Inner.Generate(app)
	if err != nil {
		return nil, err
	}
	for _, r := range resources {
		setForceEnabled(*r)
	}
	return resources, nil
}

// postAugmentLayout annotates every resource on l and its child layouts after
// the inner LayoutAugmenter ran. The layout is this component's alone, for the
// reason pruneProtectedConfig.postAugmentLayout gives.
func (f *forceReplaceConfig) postAugmentLayout(l *layout.ManifestLayout) error {
	annotateLayout(l, setForceEnabled)
	return nil
}

func setForceEnabled(obj client.Object) {
	if obj == nil {
		return
	}
	ann := obj.GetAnnotations()
	if ann == nil {
		ann = make(map[string]string)
	}
	ann[annotationFluxForceKey] = annotationFluxForceEnabled
	obj.SetAnnotations(ann)
}
