package traits

import (
	"github.com/go-kure/kure/pkg/stack"
	"sigs.k8s.io/controller-runtime/pkg/client"

	"github.com/go-kure/launcher/pkg/oam"
)

// PruneProtectionHandler handles OAM prune-protection traits.
//
// When applied, all Kubernetes resources generated for the component are
// annotated with kustomize.toolkit.fluxcd.io/prune: disabled, preventing
// FluxCD's garbage collector from deleting them. The trait takes no properties.
type PruneProtectionHandler struct{}

// CanHandle returns true for the "prune-protection" trait type.
func (h *PruneProtectionHandler) CanHandle(traitType string) bool {
	return traitType == "prune-protection"
}

// Apply wraps app.Config with a pruneProtectedConfig decorator so that every
// resource generated by this application receives the prune-disabled annotation.
//
// Narrow scope: only resources produced by the component's own app.Config are
// annotated. Resources appended to bundle.Applications by other trait handlers
// (e.g. rbac, certificate, ingress) are not affected.
func (h *PruneProtectionHandler) Apply(_ *oam.Trait, app *stack.Application, _ *stack.Bundle) error {
	app.Config = &pruneProtectedConfig{wrapped: app.Config}
	return nil
}

// pruneProtectedConfig wraps an ApplicationConfig and injects
// stack.AnnotationFluxPruneKey = stack.AnnotationFluxPruneDisabled into every
// resource returned by the wrapped config's Generate method.
type pruneProtectedConfig struct {
	wrapped stack.ApplicationConfig
}

func (p *pruneProtectedConfig) Generate(app *stack.Application) ([]*client.Object, error) {
	resources, err := p.wrapped.Generate(app)
	if err != nil {
		return nil, err
	}
	for _, r := range resources {
		ann := (*r).GetAnnotations()
		if ann == nil {
			ann = make(map[string]string)
		}
		ann[stack.AnnotationFluxPruneKey] = stack.AnnotationFluxPruneDisabled
		(*r).SetAnnotations(ann)
	}
	return resources, nil
}

// Validate delegates to the wrapped config's Validate if it implements
// stack.Validator, preserving any pre-generation validation defined there.
func (p *pruneProtectedConfig) Validate() error {
	if v, ok := p.wrapped.(stack.Validator); ok {
		return v.Validate()
	}
	return nil
}

// SetFluxNamespace forwards the per-request Flux namespace to the wrapped
// config when it satisfies fluxNamespaceSettable (e.g. HelmchartConfig).
func (p *pruneProtectedConfig) SetFluxNamespace(ns string) {
	if setter, ok := p.wrapped.(fluxNamespaceSettable); ok {
		setter.SetFluxNamespace(ns)
	}
}

// EmitsAutoHealthCheck forwards the wrapped config's auto-health-check veto so a
// prune-protected helmchart with delivery=template still suppresses the bogus
// HelmRelease health check. Defaults to true when the inner config lacks it.
func (p *pruneProtectedConfig) EmitsAutoHealthCheck() bool {
	if e, ok := p.wrapped.(autoHealthCheckEmitter); ok {
		return e.EmitsAutoHealthCheck()
	}
	return true
}
