package traits

import (
	"github.com/go-kure/kure/pkg/stack"
	"sigs.k8s.io/controller-runtime/pkg/client"

	"github.com/go-kure/launcher/pkg/oam"
)

// PruneProtectionHandler handles OAM prune-protection traits.
//
// When applied, all Kubernetes resources generated for the component are
// annotated with kustomize.toolkit.fluxcd.io/prune: disabled, preventing
// FluxCD's garbage collector from deleting them. The trait takes no properties.
type PruneProtectionHandler struct{}

// CanHandle returns true for the "prune-protection" trait type.
func (h *PruneProtectionHandler) CanHandle(traitType string) bool {
	return traitType == "prune-protection"
}

// PropertySchema declares the prune-protection trait's properties. It accepts no
// user-facing properties (it is a pure decorator), so the schema is empty.
func (h *PruneProtectionHandler) PropertySchema() map[string]oam.PropertySchema {
	return map[string]oam.PropertySchema{}
}

// Apply wraps app.Config with a pruneProtectedConfig decorator so that every
// resource generated by this application receives the prune-disabled annotation.
//
// Narrow scope: only resources produced by the component's own app.Config are
// annotated. Resources appended to bundle.Applications by other trait handlers
// (e.g. rbac, certificate, ingress) are not affected.
func (h *PruneProtectionHandler) Apply(_ *oam.Trait, app *stack.Application, _ *stack.Bundle) error {
	app.Config = wrapIfAugmenter(
		&pruneProtectedConfig{decoratorBase: decoratorBase{Inner: app.Config}},
		app.Config)
	return nil
}

// pruneProtectedConfig wraps an ApplicationConfig and injects
// stack.AnnotationFluxPruneKey = stack.AnnotationFluxPruneDisabled into every
// resource returned by the wrapped config's Generate method.
type pruneProtectedConfig struct {
	decoratorBase
}

func (p *pruneProtectedConfig) Generate(app *stack.Application) ([]*client.Object, error) {
	resources, err := p.Inner.Generate(app)
	if err != nil {
		return nil, err
	}
	for _, r := range resources {
		ann := (*r).GetAnnotations()
		if ann == nil {
			ann = make(map[string]string)
		}
		ann[stack.AnnotationFluxPruneKey] = stack.AnnotationFluxPruneDisabled
		(*r).SetAnnotations(ann)
	}
	return resources, nil
}
