package traits

import (
	"github.com/go-kure/kure/pkg/stack"
	"sigs.k8s.io/controller-runtime/pkg/client"

	"github.com/go-kure/launcher/pkg/oam"
)

// PruneProtectionHandler handles OAM prune-protection traits.
//
// When applied, all Kubernetes resources generated for the component are
// annotated with kustomize.toolkit.fluxcd.io/prune: disabled, preventing
// FluxCD's garbage collector from deleting them. The trait takes no properties.
type PruneProtectionHandler struct{}

// CanHandle returns true for the "prune-protection" trait type.
func (h *PruneProtectionHandler) CanHandle(traitType string) bool {
	return traitType == "prune-protection"
}

// Apply wraps app.Config with a pruneProtectedConfig decorator so that every
// resource generated by this application receives the prune-disabled annotation.
func (h *PruneProtectionHandler) Apply(_ *oam.Trait, app *stack.Application, _ *stack.Bundle) error {
	app.Config = &pruneProtectedConfig{wrapped: app.Config}
	return nil
}

// pruneProtectedConfig wraps an ApplicationConfig and injects
// stack.AnnotationFluxPruneKey = stack.AnnotationFluxPruneDisabled into every
// resource returned by the wrapped config's Generate method.
type pruneProtectedConfig struct {
	wrapped stack.ApplicationConfig
}

func (p *pruneProtectedConfig) Generate(app *stack.Application) ([]*client.Object, error) {
	resources, err := p.wrapped.Generate(app)
	if err != nil {
		return nil, err
	}
	for _, r := range resources {
		ann := (*r).GetAnnotations()
		if ann == nil {
			ann = make(map[string]string)
		}
		ann[stack.AnnotationFluxPruneKey] = stack.AnnotationFluxPruneDisabled
		(*r).SetAnnotations(ann)
	}
	return resources, nil
}

// Validate delegates to the wrapped config's Validate if it implements
// stack.Validator, preserving any pre-generation validation defined there.
func (p *pruneProtectedConfig) Validate() error {
	if v, ok := p.wrapped.(stack.Validator); ok {
		return v.Validate()
	}
	return nil
}
