package traits

import (
	"math"

	appsv1 "k8s.io/api/apps/v1"
	batchv1 "k8s.io/api/batch/v1"
	corev1 "k8s.io/api/core/v1"
	"sigs.k8s.io/controller-runtime/pkg/client"

	"github.com/go-kure/kure/pkg/kubernetes"
	"github.com/go-kure/kure/pkg/stack"

	"github.com/go-kure/launcher/pkg/errors"
	"github.com/go-kure/launcher/pkg/oam"
)

// SecurityContextHandler handles OAM security-context traits.
//
// The trait declares the workload's required PSA level and applies a matching
// security context to all PodSpec-bearing resources generated by the underlying
// component config. This prevents crane's securityContextMutator from overwriting
// them with restricted defaults — the mutator only fires when SecurityContext is nil.
//
// The psaLevel property relaxes namespace PSA admission labels and crane's
// CheckPSAMaxProfile gate. It does NOT permit privileged container patterns
// (hostNetwork, hostPID, privileged mode, etc.); those remain controlled by
// SecurityPolicy.AllowPrivileged and related fields.
type SecurityContextHandler struct{}

// CanHandle returns true for the "security-context" trait type.
func (h *SecurityContextHandler) CanHandle(traitType string) bool {
	return traitType == "security-context"
}

// Apply wraps app.Config so that Generate() produces securityContext values
// matching the declared psaLevel rather than the crane-default restricted.
// It does NOT create additional Kubernetes objects.
func (h *SecurityContextHandler) Apply(trait *oam.Trait, app *stack.Application, _ *stack.Bundle) error {
	spec, err := parseSecurityContextProperties(trait.Properties)
	if err != nil {
		return err
	}
	app.Config = &securityContextConfig{inner: app.Config, spec: spec}
	return nil
}

// securityContextSpec holds the parsed trait properties.
type securityContextSpec struct {
	PSALevel                 kubernetes.PSALevel
	RunAsNonRoot             *bool
	AllowPrivilegeEscalation *bool
	ReadOnlyRootFilesystem   *bool
	RunAsUser                *int64
	RunAsGroup               *int64
	FsGroup                  *int64
}

// parseSecurityContextProperties parses trait.Properties and validates constraints.
func parseSecurityContextProperties(props map[string]any) (securityContextSpec, error) {
	var spec securityContextSpec

	levelRaw, ok := props["psaLevel"]
	if !ok {
		return spec, errors.New("security-context: psaLevel is required")
	}
	levelStr, ok := levelRaw.(string)
	if !ok {
		return spec, errors.Errorf("security-context: psaLevel must be a string, got %T", levelRaw)
	}
	switch kubernetes.PSALevel(levelStr) {
	case kubernetes.PSARestricted, kubernetes.PSABaseline, kubernetes.PSAPrivileged:
		spec.PSALevel = kubernetes.PSALevel(levelStr)
	default:
		return spec, errors.Errorf("security-context: psaLevel %q is invalid; must be restricted, baseline, or privileged", levelStr)
	}

	if v, ok := props["runAsNonRoot"]; ok {
		b, ok := v.(bool)
		if !ok {
			return spec, errors.Errorf("security-context: runAsNonRoot must be a bool, got %T", v)
		}
		spec.RunAsNonRoot = &b
	}
	if v, ok := props["allowPrivilegeEscalation"]; ok {
		b, ok := v.(bool)
		if !ok {
			return spec, errors.Errorf("security-context: allowPrivilegeEscalation must be a bool, got %T", v)
		}
		spec.AllowPrivilegeEscalation = &b
	}
	if v, ok := props["readOnlyRootFilesystem"]; ok {
		b, ok := v.(bool)
		if !ok {
			return spec, errors.Errorf("security-context: readOnlyRootFilesystem must be a bool, got %T", v)
		}
		spec.ReadOnlyRootFilesystem = &b
	}
	if v, ok := props["runAsUser"]; ok {
		n, err := toInt64(v)
		if err != nil {
			return spec, errors.Errorf("security-context: runAsUser: %v", err)
		}
		spec.RunAsUser = &n
	}
	if v, ok := props["runAsGroup"]; ok {
		n, err := toInt64(v)
		if err != nil {
			return spec, errors.Errorf("security-context: runAsGroup: %v", err)
		}
		spec.RunAsGroup = &n
	}
	if v, ok := props["fsGroup"]; ok {
		n, err := toInt64(v)
		if err != nil {
			return spec, errors.Errorf("security-context: fsGroup: %v", err)
		}
		spec.FsGroup = &n
	}

	if err := validateSecurityContextSpec(spec); err != nil {
		return spec, err
	}

	return spec, nil
}

// validateSecurityContextSpec rejects overrides that contradict the declared psaLevel.
func validateSecurityContextSpec(spec securityContextSpec) error {
	if spec.PSALevel == kubernetes.PSARestricted {
		if spec.AllowPrivilegeEscalation != nil && *spec.AllowPrivilegeEscalation {
			return errors.New("security-context: allowPrivilegeEscalation: true is incompatible with psaLevel restricted")
		}
		if spec.RunAsNonRoot != nil && !*spec.RunAsNonRoot {
			return errors.New("security-context: runAsNonRoot: false is incompatible with psaLevel restricted")
		}
		if spec.ReadOnlyRootFilesystem != nil && !*spec.ReadOnlyRootFilesystem {
			return errors.New("security-context: readOnlyRootFilesystem: false is incompatible with psaLevel restricted")
		}
	}
	return nil
}

// securityContextConfig wraps an ApplicationConfig and sets PSA-appropriate
// SecurityContext fields on all PodSpec-bearing resources at Generate time.
type securityContextConfig struct {
	inner stack.ApplicationConfig
	spec  securityContextSpec
}

// Generate delegates to the inner config and then applies the security context
// overrides to all PodSpec-bearing resources.
func (c *securityContextConfig) Generate(app *stack.Application) ([]*client.Object, error) {
	objects, err := c.inner.Generate(app)
	if err != nil {
		return nil, err
	}
	for _, objPtr := range objects {
		if podSpec := extractPodSpecSC(*objPtr); podSpec != nil {
			c.spec.applyToPodSpec(podSpec)
		}
	}
	return objects, nil
}

// Validate delegates to the wrapped config's Validate if it implements
// stack.Validator.
func (c *securityContextConfig) Validate() error {
	if v, ok := c.inner.(stack.Validator); ok {
		return v.Validate()
	}
	return nil
}

// SetFluxNamespace forwards to the inner config when it is fluxNamespaceSettable.
func (c *securityContextConfig) SetFluxNamespace(ns string) {
	if setter, ok := c.inner.(fluxNamespaceSettable); ok {
		setter.SetFluxNamespace(ns)
	}
}

// EmitsAutoHealthCheck forwards the inner config's veto; defaults to true.
func (c *securityContextConfig) EmitsAutoHealthCheck() bool {
	if e, ok := c.inner.(autoHealthCheckEmitter); ok {
		return e.EmitsAutoHealthCheck()
	}
	return true
}

// applyToPodSpec sets SecurityContext fields on the pod and all containers
// (including init containers). Non-nil contexts are set so that crane's
// securityContextMutator (which only fires when SecurityContext is nil) skips them.
func (s *securityContextSpec) applyToPodSpec(podSpec *corev1.PodSpec) {
	podSC := s.buildPodSecurityContext()
	podSpec.SecurityContext = podSC

	containerSC := s.buildContainerSecurityContext()
	for i := range podSpec.Containers {
		podSpec.Containers[i].SecurityContext = containerSC
	}
	for i := range podSpec.InitContainers {
		podSpec.InitContainers[i].SecurityContext = containerSC
	}
}

// buildPodSecurityContext returns the pod-level security context for the spec.
func (s *securityContextSpec) buildPodSecurityContext() *corev1.PodSecurityContext {
	switch s.PSALevel {
	case kubernetes.PSARestricted:
		sc := kubernetes.RestrictedPodSecurityContext()
		if s.RunAsNonRoot != nil {
			sc.RunAsNonRoot = s.RunAsNonRoot
		}
		if s.RunAsUser != nil {
			sc.RunAsUser = s.RunAsUser
		}
		if s.RunAsGroup != nil {
			sc.RunAsGroup = s.RunAsGroup
		}
		if s.FsGroup != nil {
			sc.FSGroup = s.FsGroup
		}
		return sc

	default: // PSABaseline or PSAPrivileged
		// Minimal non-nil context: does NOT include restricted-only fields
		// (RunAsNonRoot, SeccompProfile). Crane's mutator skips non-nil contexts.
		sc := &corev1.PodSecurityContext{}
		if s.RunAsUser != nil {
			sc.RunAsUser = s.RunAsUser
		}
		if s.RunAsGroup != nil {
			sc.RunAsGroup = s.RunAsGroup
		}
		if s.FsGroup != nil {
			sc.FSGroup = s.FsGroup
		}
		return sc
	}
}

// buildContainerSecurityContext returns the container-level security context for the spec.
func (s *securityContextSpec) buildContainerSecurityContext() *corev1.SecurityContext {
	switch s.PSALevel {
	case kubernetes.PSARestricted:
		sc := kubernetes.RestrictedSecurityContext()
		if s.AllowPrivilegeEscalation != nil {
			sc.AllowPrivilegeEscalation = s.AllowPrivilegeEscalation
		}
		if s.RunAsNonRoot != nil {
			sc.RunAsNonRoot = s.RunAsNonRoot
		}
		if s.ReadOnlyRootFilesystem != nil {
			sc.ReadOnlyRootFilesystem = s.ReadOnlyRootFilesystem
		}
		return sc

	default: // PSABaseline or PSAPrivileged
		// Minimal non-nil context: does NOT include AllowPrivilegeEscalation,
		// ReadOnlyRootFilesystem, Capabilities.Drop, or SeccompProfile
		// (those are restricted-only requirements). Non-nil is sufficient to
		// prevent crane's securityContextMutator from overwriting with restricted defaults.
		sc := &corev1.SecurityContext{}
		if s.AllowPrivilegeEscalation != nil {
			sc.AllowPrivilegeEscalation = s.AllowPrivilegeEscalation
		}
		if s.ReadOnlyRootFilesystem != nil {
			sc.ReadOnlyRootFilesystem = s.ReadOnlyRootFilesystem
		}
		return sc
	}
}

// extractPodSpecSC returns the PodSpec from a PodSpec-bearing resource, or nil.
func extractPodSpecSC(obj client.Object) *corev1.PodSpec {
	switch o := obj.(type) {
	case *appsv1.Deployment:
		return &o.Spec.Template.Spec
	case *appsv1.StatefulSet:
		return &o.Spec.Template.Spec
	case *appsv1.DaemonSet:
		return &o.Spec.Template.Spec
	case *batchv1.Job:
		return &o.Spec.Template.Spec
	case *batchv1.CronJob:
		return &o.Spec.JobTemplate.Spec.Template.Spec
	default:
		return nil
	}
}

func toInt64(v any) (int64, error) {
	switch n := v.(type) {
	case int:
		return int64(n), nil
	case int32:
		return int64(n), nil
	case int64:
		return n, nil
	case float64:
		if n != math.Trunc(n) {
			return 0, errors.Errorf("expected integer, got non-integral float %v", n)
		}
		return int64(n), nil
	default:
		return 0, errors.Errorf("expected integer, got %T", v)
	}
}
