#!/usr/bin/env bash
# check-issue-refs.sh — rejects issue and PR references that do not name their
# repository (go-kure/launcher#400).
#
# A bare `#N` resolves against whichever repository the reader happens to be in,
# and `go doc`, pkg.go.dev and `go test` output have no repository at all. An
# ownerless `launcher#N` or `kure#N` names a repository but GitHub does not link
# it. Write `go-kure/launcher#N`, or `owner/repo#N` for another repository.
#
# Scans the whole tree, not changed lines, so a PR and the merge queue get the
# same result (the go-kure/.github scan-parity rule for gates).
#
# Scope: tracked *.go *.md *.sh *.yml *.yaml *.toml *.json, except CHANGELOG.md
# (generated by git-cliff from commit subjects), anything under a testdata/
# directory, and this script and its self-test.
#
# Rejected:
#   bare     `#N` with 2 to 5 digits, not preceded by a letter, digit, `_` or `&`
#            (so `(#227)`, `#227/#242`, `pre-#444` are caught; the HTML entity
#            `&#1234;` is not)
#   ownerless  a name containing a letter, then `#N` with 2 to 5 digits, with
#              no `owner/` before it (so `launcher#278`, `kure#539`,
#              `pre-launcher#278` and `...launcher#278` are caught;
#              `go-kure/launcher#278` and `owner/kure-launcher#278` are not)
# Ignored before matching, because each is a location or code, not a reference:
#   - a Markdown link target `](...)` with no whitespace or quote and at most one
#     level of nested parentheses, so `](#12-foo)`, `](design.md#12-foo)` and
#     `](design(v2).md#12-foo)` pass, while `f[i]("#227")` does not;
#   - a URL `scheme://...` up to whitespace, a quote or a bracket, so
#     `https://example.com/#12-foo` passes;
#   - a printf verb carrying the `#` flag, so `%#12x`, `%+#12.6g` and the
#     indexed `%#12[1]x` pass;
#   - a shell prefix trim `${name#...}` or `${name##...}`, so `${port#80}` passes.
#
# Escape hatch: `allow-ref` anywhere on the same line exempts that line. Needed
# for an all-digit CSS colour such as `#123`, which no pattern can tell apart
# from a reference.
#
# Not caught: a single-digit `#N` or `name#N` (prose such as "step #1" or a
# message such as "resolve#2" would trip it), an ownerless all-numeric
# repository name such as `123#456` (digits on both sides of `#` also occur in
# ordinary text), and a qualified `owner/repo#N` that names the wrong repository.
#
# Usage: check-issue-refs.sh [--root DIR]
# Exit:  0 clean, 1 references found, 2 usage or scan error.

set -euo pipefail

ROOT="."
while [[ $# -gt 0 ]]; do
  case "$1" in
    --root) ROOT="${2:-}"; [[ -n "$ROOT" ]] || { echo "ERROR: --root needs a directory" >&2; exit 2; }; shift 2 ;;
    -h|--help) sed -n '2,/^# Exit:/p' "$0"; exit 0 ;;
    *) echo "ERROR: unknown argument: $1" >&2; exit 2 ;;
  esac
done

BARE='(^|[^A-Za-z0-9_&])#[0-9]{2,5}([^A-Za-z0-9_]|$)'
PART='(^|[^A-Za-z0-9_./-])[A-Za-z0-9_.-]*[A-Za-z][A-Za-z0-9_.-]*#[0-9]{2,5}([^A-Za-z0-9_]|$)'

# Strippers: group 1 is the text before the match, the last group the text after.
LINK='^(.*)\]\(([^()[:space:]"'"'"'`]|\([^()[:space:]"'"'"'`]*\))*\)(.*)$'
URL='^(.*)[A-Za-z][A-Za-z0-9+.-]*://[^[:space:]<>()"'"'"'`]*(.*)$'
VERB='^(.*)%[-+ 0]*#[-+ #0]*(\[[0-9]+\])?[0-9]*(\.[0-9]*)?(\[[0-9]+\])?[A-Za-z](.*)$'
TRIM='^(.*)\$\{[A-Za-z_][A-Za-z0-9_]*##?[^}]*\}(.*)$'

hits="$(mktemp)"
trap 'rm -f "$hits"' EXIT

# git grep finds the candidate lines; the loop below drops anchors and pragmas.
# -z separates file name, line number and text with NUL, so a `:` in a file name
# cannot shift the fields. Exit 1 means no candidate at all; above 1 is an error.
rc=0
git -C "$ROOT" grep -z --no-color -n -I -E -e "$BARE" -e "$PART" -- \
  '*.go' '*.md' '*.sh' '*.yml' '*.yaml' '*.toml' '*.json' \
  ':!CHANGELOG.md' ':!testdata/*' ':!*/testdata/*' \
  ':!scripts/check-issue-refs.sh' ':!scripts/check-issue-refs-test.sh' >"$hits" || rc=$?
if [[ "$rc" -gt 1 ]]; then
  echo "ERROR: git grep failed in $ROOT (exit $rc)" >&2
  exit 2
fi

found=0
while IFS= read -r -d '' file && IFS= read -r -d '' lineno && IFS= read -r text; do
  [[ "$text" == *allow-ref* ]] && continue
  stripped="$text"
  # Each pass removes one match, so every loop ends.
  while [[ "$stripped" =~ $LINK ]]; do
    stripped="${BASH_REMATCH[1]}]${BASH_REMATCH[3]}"
  done
  while [[ "$stripped" =~ $URL ]]; do
    stripped="${BASH_REMATCH[1]}${BASH_REMATCH[2]}"
  done
  while [[ "$stripped" =~ $VERB ]]; do
    stripped="${BASH_REMATCH[1]}${BASH_REMATCH[5]}"
  done
  while [[ "$stripped" =~ $TRIM ]]; do
    stripped="${BASH_REMATCH[1]}${BASH_REMATCH[2]}"
  done
  if [[ "$stripped" =~ $BARE || "$stripped" =~ $PART ]]; then
    echo "$file:$lineno: $text"
    found=$((found + 1))
  fi
done <"$hits"

if [[ "$found" -gt 0 ]]; then
  echo "" >&2
  echo "check-issue-refs: $found line(s) with a bare #N or ownerless repo#N reference." >&2
  echo "Write go-kure/launcher#N (or owner/repo#N), or add allow-ref to a line that is not a reference." >&2
  exit 1
fi
echo "check-issue-refs: OK"
