#!/usr/bin/env bash
# check-issue-refs.sh — rejects issue and PR references that do not name their
# repository (go-kure/launcher#400).
#
# A bare `#N` resolves against whichever repository the reader happens to be in,
# and `go doc`, pkg.go.dev and `go test` output have no repository at all. An
# ownerless `launcher#N` or `kure#N` names a repository but GitHub does not link
# it. Write `go-kure/launcher#N`, or `owner/repo#N` for another repository.
#
# Two modes, each run on its own:
#
# Tree (default). Scans the whole tree, not changed lines, so a PR and the
# merge queue get the same result (the go-kure/.github scan-parity rule for
# gates). Scope: tracked *.go *.md *.sh *.yml *.yaml *.toml *.json, except
# CHANGELOG.md (generated by git-cliff from commit subjects), anything under a
# testdata/ directory, and this script and its self-test.
#
# Commits (`--commits [BASE]`, go-kure/launcher#732). Scans every line of each
# non-merge commit message in BASE..HEAD (BASE defaults to origin/main; `--head`
# sets the other end), so a bare reference fails before the first push, while an
# amend still costs nothing. Commits authored by Renovate
# (renovate@whitesourcesoftware.com) are skipped: their messages are generated.
# A BASE or HEAD that does not resolve is an error (exit 2), never a pass. A stale
# local origin/main widens the range to commits that are already on main; the
# failure message says so.
#
# Rejected:
#   bare     `#N` with 2 to 5 digits, not preceded by a letter, digit, `_` or `&`
#            (so `(#227)`, `#227/#242`, `pre-#444` are caught; the HTML entity
#            `&#1234;` is not)
#   ownerless  a name containing a letter, then `#N` with 2 to 5 digits, with
#              no `owner/` before it (so `launcher#278`, `kure#539`,
#              `pre-launcher#278` and `...launcher#278` are caught;
#              `go-kure/launcher#278` and `owner/kure-launcher#278` are not)
#   emphasised  either of the above wrapped in single underscores, which the
#               two patterns miss because `_` counts as part of a word; the
#               opening `_` must not follow a letter, digit, `_`, `&`, `.`, `/`
#               or `-` (so `_#227_`, `_kure#539_` and `_my_repo#539_` are
#               caught; `__#12__`, `a_#12_b`, `_go-kure/kure#539_` and
#               `_owner/_repo#539_` are not)
# Ignored before matching, because each is a location or code, not a reference:
#   - a Markdown link target `](...)` with no whitespace or quote and at most one
#     level of nested parentheses, so `](#12-foo)`, `](design.md#12-foo)` and
#     `](design(v2).md#12-foo)` pass, while `f[i]("#227")` does not;
#   - a URL `scheme://...` up to whitespace, a quote or a bracket, so
#     `https://example.com/#12-foo` passes;
#   - a printf verb carrying the `#` flag, so `%#12x`, `%+#12.6g`, the indexed
#     `%#12[1]x` and the `*` width or precision `%#12.*x` pass;
#   - a shell prefix trim `${name#...}` or `${name##...}`, also on an array
#     element whose subscript holds no `#`, so `${port#80}` and
#     `${items[0]#80}` pass while `${items["see #227"]#80}` does not.
#
# Escape hatch: `allow-ref` anywhere on the same line exempts that line. Needed
# for an all-digit CSS colour such as `#123`, which no pattern can tell apart
# from a reference, and for a bare URL with parentheses before its fragment,
# such as `https://example.com/v2_(legacy)#123`: the URL ends at the `(`, so
# `)#123` reads as a reference. A Markdown link around the URL also works.
#
# Not caught: a single-digit `#N` or `name#N` (prose such as "step #1" or a
# message such as "resolve#2" would trip it), an ownerless all-numeric
# repository name such as `123#456` (digits on both sides of `#` also occur in
# ordinary text), a qualified `owner/repo#N` that names the wrong repository,
# and any reference inside a shell trim's pattern, with or without a subscript
# (`${x# see #227}`, `${items[0]# see #227}`), quoting included
# (`echo "${x#" "see #227" "}"`; telling those apart needs quote-aware parsing).
#
# Usage: check-issue-refs.sh [--root DIR] [--commits [BASE] [--head REV]]
# Exit:  0 clean, 1 references found, 2 usage or scan error.

set -euo pipefail

ROOT="."
MODE="tree"
BASE="origin/main"
HEAD_REV=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --root) ROOT="${2:-}"; [[ -n "$ROOT" ]] || { echo "ERROR: --root needs a directory" >&2; exit 2; }; shift 2 ;;
    --commits)
      MODE="commits"
      if [[ $# -ge 2 && "$2" != -* ]]; then BASE="$2"; shift; fi
      shift ;;
    --head) HEAD_REV="${2:-}"; [[ -n "$HEAD_REV" ]] || { echo "ERROR: --head needs a revision" >&2; exit 2; }; shift 2 ;;
    -h|--help) sed -n '2,/^# Exit:/p' "$0"; exit 0 ;;
    *) echo "ERROR: unknown argument: $1" >&2; exit 2 ;;
  esac
done
if [[ -n "$HEAD_REV" && "$MODE" != "commits" ]]; then
  echo "ERROR: --head applies only with --commits" >&2
  exit 2
fi
HEAD_REV="${HEAD_REV:-HEAD}"

BARE='(^|[^A-Za-z0-9_&])#[0-9]{2,5}([^A-Za-z0-9_]|$)'
PART='(^|[^A-Za-z0-9_./-])[A-Za-z0-9_.-]*[A-Za-z][A-Za-z0-9_.-]*#[0-9]{2,5}([^A-Za-z0-9_]|$)'
EMPH='(^|[^A-Za-z0-9_&./-])_([A-Za-z0-9_.-]*[A-Za-z][A-Za-z0-9_.-]*)?#[0-9]{2,5}_([^A-Za-z0-9_]|$)'

# Strippers: group 1 is the text before the match, the last group the text after.
LINK='^(.*)\]\(([^()[:space:]"'"'"'`]|\([^()[:space:]"'"'"'`]*\))*\)(.*)$'
URL='^(.*)[A-Za-z][A-Za-z0-9+.-]*://[^[:space:]<>()"'"'"'`]*(.*)$'
VERB='^(.*)%[-+ 0]*#[-+ #0]*(\[[0-9]+\])?(\*|[0-9]*)(\.(\[[0-9]+\])?(\*|[0-9]*))?(\[[0-9]+\])?[A-Za-z](.*)$'
TRIM='^(.*)\$\{[A-Za-z_][A-Za-z0-9_]*(\[[^]}#]*\])?##?[^}]*\}(.*)$'

RENOVATE_EMAIL="renovate@whitesourcesoftware.com"

# has_ref TEXT: succeeds when TEXT holds a reference once pragmas, anchors, URLs,
# format verbs and shell trims are dropped. Both modes judge a line with it.
has_ref() {
  local stripped="$1"
  [[ "$stripped" == *allow-ref* ]] && return 1
  # Each pass removes one match, so every loop ends.
  while [[ "$stripped" =~ $LINK ]]; do
    stripped="${BASH_REMATCH[1]}]${BASH_REMATCH[3]}"
  done
  while [[ "$stripped" =~ $URL ]]; do
    stripped="${BASH_REMATCH[1]}${BASH_REMATCH[2]}"
  done
  while [[ "$stripped" =~ $VERB ]]; do
    stripped="${BASH_REMATCH[1]}${BASH_REMATCH[8]}"
  done
  while [[ "$stripped" =~ $TRIM ]]; do
    stripped="${BASH_REMATCH[1]}${BASH_REMATCH[3]}"
  done
  [[ "$stripped" =~ $BARE || "$stripped" =~ $PART || "$stripped" =~ $EMPH ]]
}

scan_tree() {
  local rc=0 file lineno text
  # Global, not local: the EXIT trap runs after this function has returned.
  hits="$(mktemp)"
  trap 'rm -f "$hits"' EXIT

  # git grep finds the candidate lines; has_ref drops anchors and pragmas.
  # -z separates file name, line number and text with NUL, so a `:` in a file name
  # cannot shift the fields. Exit 1 means no candidate at all; above 1 is an error.
  git -C "$ROOT" grep -z --no-color -n -I -E -e "$BARE" -e "$PART" -e "$EMPH" -- \
    '*.go' '*.md' '*.sh' '*.yml' '*.yaml' '*.toml' '*.json' \
    ':!CHANGELOG.md' ':!testdata/*' ':!*/testdata/*' \
    ':!scripts/check-issue-refs.sh' ':!scripts/check-issue-refs-test.sh' >"$hits" || rc=$?
  if [[ "$rc" -gt 1 ]]; then
    echo "ERROR: git grep failed in $ROOT (exit $rc)" >&2
    exit 2
  fi

  found=0
  while IFS= read -r -d '' file && IFS= read -r -d '' lineno && IFS= read -r text; do
    if has_ref "$text"; then
      echo "$file:$lineno: $text"
      found=$((found + 1))
    fi
  done <"$hits"

  if [[ "$found" -gt 0 ]]; then
    echo "" >&2
    echo "check-issue-refs: $found line(s) with a bare #N or ownerless repo#N reference." >&2
    echo "Write go-kure/launcher#N (or owner/repo#N), or add allow-ref to a line that is not a reference." >&2
    exit 1
  fi
  echo "check-issue-refs: OK"
}

# resolve REV: the commit REV names in ROOT, or exit 2.
resolve() {
  local oid
  if ! oid="$(git -C "$ROOT" rev-parse --verify --quiet "$1^{commit}")"; then
    echo "ERROR: '$1' is not a commit in $ROOT; run git fetch origin, or pass --commits <base>" >&2
    exit 2
  fi
  printf '%s\n' "$oid"
}

scan_commits() {
  local base head commits commit meta email subject message line scanned=0 skipped=0
  # resolve runs in a subshell, so its exit only ends that; pass the status on.
  base="$(resolve "$BASE")" || exit 2
  head="$(resolve "$HEAD_REV")" || exit 2
  if ! commits="$(git -C "$ROOT" rev-list --no-merges "$base..$head")"; then
    echo "ERROR: git rev-list $BASE..$HEAD_REV failed in $ROOT" >&2
    exit 2
  fi

  found=0
  while IFS= read -r commit; do
    [[ -n "$commit" ]] || continue
    # %ae and %s on one line: an email holds no newline, and a subject is one line.
    if ! meta="$(git -C "$ROOT" log -1 --format='%ae %s' "$commit")" ||
       ! message="$(git -C "$ROOT" log -1 --format='%B' "$commit")"; then
      echo "ERROR: cannot read commit $commit in $ROOT" >&2
      exit 2
    fi
    email="${meta%% *}"
    subject="${meta#* }"
    if [[ "${email,,}" == "$RENOVATE_EMAIL" ]]; then
      skipped=$((skipped + 1))
      continue
    fi
    scanned=$((scanned + 1))
    while IFS= read -r line; do
      if has_ref "$line"; then
        echo "${commit:0:8} ($subject): $line"
        found=$((found + 1))
      fi
    done <<<"$message"
  done <<<"$commits"

  if [[ "$found" -gt 0 ]]; then
    echo "" >&2
    echo "check-issue-refs: $found commit message line(s) in $BASE..$HEAD_REV with a bare #N or ownerless repo#N reference." >&2
    echo "Reword them to go-kure/launcher#N (or owner/repo#N) with git commit --amend or git rebase -i, or add allow-ref to a line that is not a reference." >&2
    echo "A flagged commit that is already on main means $BASE is stale: run git fetch origin and re-run." >&2
    exit 1
  fi
  echo "check-issue-refs: OK ($scanned commit message(s) in $BASE..$HEAD_REV, $skipped Renovate commit(s) skipped)"
}

if [[ "$MODE" == "commits" ]]; then
  scan_commits
else
  scan_tree
fi
