#!/usr/bin/env bash
# check-issue-refs.sh — rejects issue and PR references that do not name their
# repository (go-kure/launcher#400).
#
# A bare `#N` resolves against whichever repository the reader happens to be in,
# and `go doc`, pkg.go.dev and `go test` output have no repository at all. A
# partial `launcher#N` names the repository but GitHub does not link it. Write
# `go-kure/launcher#N`, or `owner/repo#N` for another repository.
#
# Scans the whole tree, not changed lines, so a PR and the merge queue get the
# same result (the go-kure/.github scan-parity rule for gates).
#
# Scope: tracked *.go *.md *.sh *.yml *.yaml *.toml *.json, except CHANGELOG.md
# (generated by git-cliff from commit subjects), anything under a testdata/
# directory, and this script and its self-test.
#
# Rejected:
#   bare     `#N` with 2 to 5 digits, not preceded by a letter, digit, `_`, `&`
#            or `%` (so `(#227)`, `#227/#242`, `pre-#444` are caught; the HTML
#            entity `&#1234;` and the Go format verb `%#12x` are not)
#   partial  `launcher#N` not preceded by `/` or by a letter, digit or `_`
# A Markdown link target `](#...)` is an anchor, not a reference, and is ignored.
#
# Escape hatch: `allow-ref` anywhere on the same line exempts that line. Needed
# for an all-digit CSS colour such as `#123`, which no pattern can tell apart
# from a reference.
#
# Not caught: a single-digit `#N` (prose such as "step #1" would trip it), and a
# qualified `owner/repo#N` that names the wrong repository.
#
# Usage: check-issue-refs.sh [--root DIR]
# Exit:  0 clean, 1 references found, 2 usage or scan error.

set -euo pipefail

ROOT="."
while [[ $# -gt 0 ]]; do
  case "$1" in
    --root) ROOT="${2:-}"; [[ -n "$ROOT" ]] || { echo "ERROR: --root needs a directory" >&2; exit 2; }; shift 2 ;;
    -h|--help) sed -n '2,28p' "$0"; exit 0 ;;
    *) echo "ERROR: unknown argument: $1" >&2; exit 2 ;;
  esac
done

BARE='(^|[^A-Za-z0-9_&%])#[0-9]{2,5}([^A-Za-z0-9_]|$)'
PART='(^|[^A-Za-z0-9_/])launcher#[0-9]+'

hits="$(mktemp)"
trap 'rm -f "$hits"' EXIT

# git grep finds the candidate lines; the loop below drops anchors and pragmas.
# -z separates file name, line number and text with NUL, so a `:` in a file name
# cannot shift the fields. Exit 1 means no candidate at all; above 1 is an error.
rc=0
git -C "$ROOT" grep -z --no-color -n -I -E -e "$BARE" -e "$PART" -- \
  '*.go' '*.md' '*.sh' '*.yml' '*.yaml' '*.toml' '*.json' \
  ':!CHANGELOG.md' ':!testdata/*' ':!*/testdata/*' \
  ':!scripts/check-issue-refs.sh' ':!scripts/check-issue-refs-test.sh' >"$hits" || rc=$?
if [[ "$rc" -gt 1 ]]; then
  echo "ERROR: git grep failed in $ROOT (exit $rc)" >&2
  exit 2
fi

found=0
while IFS= read -r -d '' file && IFS= read -r -d '' lineno && IFS= read -r text; do
  [[ "$text" == *allow-ref* ]] && continue
  stripped="$text"
  while [[ "$stripped" =~ ^(.*)\]\(#[^\)]*\)(.*)$ ]]; do
    stripped="${BASH_REMATCH[1]}]${BASH_REMATCH[2]}"
  done
  if [[ "$stripped" =~ $BARE || "$stripped" =~ $PART ]]; then
    echo "$file:$lineno: $text"
    found=$((found + 1))
  fi
done <"$hits"

if [[ "$found" -gt 0 ]]; then
  echo "" >&2
  echo "check-issue-refs: $found line(s) with a bare #N or partial launcher#N reference." >&2
  echo "Write go-kure/launcher#N (or owner/repo#N), or add allow-ref to a line that is not a reference." >&2
  exit 1
fi
echo "check-issue-refs: OK"
