package kurel

import (
	"strings"
	"testing"
)

// An authored trait object name (go-kure/launcher#787) is checked against the
// other objects of the document by the in-document collision check, as a default
// name is: Transform alone compares nothing across components.

// webBesideAPI is component web, whose trait is given, beside component
// api carrying the same trait with default names.
func webBesideAPI(webTrait, apiTrait string) string {
	return duplicateApp(`    - name: web
      type: webservice
      properties:
        image: ghcr.io/example/web:v1.0.0
        port: 8080
      traits:
`+webTrait+`    - name: api
      type: webservice
      properties:
        image: ghcr.io/example/api:v1.0.0
        port: 8080
      traits:
`+apiTrait, "", "")
}

const (
	scalerTrait = `        - type: scaler
          properties:
            minReplicas: 2
            maxReplicas: 4
            enablePDB: true
`
	rbacTrait = `        - type: rbac
          properties:
            clusterWide: true
            rules:
              - apiGroups: [""]
                resources: [pods]
                verbs: [get]
`
	networkPolicyTrait = `        - type: networkpolicy
          properties:
            ingress: []
`
)

func TestAuthoredTraitName_CollisionWithAnotherComponentReported(t *testing.T) {
	const rbacGroup = ".rbac.authorization.k8s.io "
	for _, tc := range []struct {
		name, trait, override, sub string
		want                       []string // each object reported, as the check names it
	}{
		{
			name: "scaler hpaName", trait: scalerTrait, override: "            hpaName: api-hpa\n", sub: "scaler",
			want: []string{`HorizontalPodAutoscaler.autoscaling "default/api-hpa"`},
		},
		{
			name: "scaler pdbName", trait: scalerTrait, override: "            pdbName: api-pdb\n", sub: "scaler",
			want: []string{`PodDisruptionBudget.policy "default/api-pdb"`},
		},
		{
			// One name for all four objects: all four collide.
			name: "rbac name", trait: rbacTrait, override: "            name: api\n", sub: "rbac",
			want: []string{
				"Role" + rbacGroup + `"default/api"`,
				"RoleBinding" + rbacGroup + `"default/api"`,
				"ClusterRole" + rbacGroup + `"api"`,
				"ClusterRoleBinding" + rbacGroup + `"api"`,
			},
		},
		{
			name: "networkpolicy name", trait: networkPolicyTrait, override: "            name: api-allow\n", sub: "networkpolicy",
			want: []string{`NetworkPolicy.networking.k8s.io "default/api-allow"`},
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			if _, err := collisionCheck(t, webBesideAPI(tc.trait, tc.trait)); err != nil {
				t.Fatalf("default names: %v, want two components with the same trait accepted", err)
			}
			_, err := collisionCheck(t, webBesideAPI(tc.trait+tc.override, tc.trait))
			if err == nil {
				t.Fatalf("an authored name equal to component api's object was accepted, want a collision on %v", tc.want)
			}
			producers := `is generated by both sub-application "web-` + tc.sub + `" of component "web" and sub-application "api-` + tc.sub + `" of component "api"`
			for _, object := range tc.want {
				if want := object + " " + producers; !strings.Contains(err.Error(), want) {
					t.Errorf("err = %v, want it to contain %q", err, want)
				}
			}
			if !strings.HasPrefix(err.Error(), "generated-object collision: ") {
				t.Errorf("err = %v, want the in-document collision check's error", err)
			}
		})
	}
}
