package kurel

import (
	"fmt"
	"strings"
	"testing"

	"github.com/go-kure/launcher/pkg/oam"
)

// These tests pin go-kure/launcher#757 through kurel's own transformer: one
// component's application and its trait sub-applications must not generate two
// objects of one group, kind, namespace and name.

// collisionCheck transforms appYAML with kurel's builtin transformer, generates
// it once and returns the in-document collision check's verdict, as runBuild
// reaches it.
func collisionCheck(t *testing.T, appYAML string) ([]oam.GeneratedApplication, error) {
	t.Helper()
	transformer := newBuiltinTransformer()
	app, err := oam.ParseWithExtraTypes([]byte(appYAML), nil, transformer.LowerableTypes())
	if err != nil {
		t.Fatalf("parsing: %v", err)
	}
	if err := transformer.ValidateAuthoredProperties(app); err != nil {
		t.Fatalf("validating: %v", err)
	}
	cluster, err := transformer.Transform(app, oam.TransformContext{Domain: kurelDomain})
	if err != nil {
		t.Fatalf("transforming: %v", err)
	}
	apps, err := oam.GenerateApplications(cluster)
	if err != nil {
		t.Fatalf("generating: %v", err)
	}
	return apps, oam.CheckInDocumentCollisions(apps)
}

// duplicateShapes are the three cluster shapes: one tier (flat), a daemonset in
// the infra tier (hierarchical), and a dependency policy (dependency-aware).
var duplicateShapes = []struct {
	name, components, policies string
}{
	{name: "flat"},
	{name: "hierarchical", components: `
    - name: agent
      type: daemonset
      properties:
        image: ghcr.io/example/agent:v1.0.0
`},
	{name: "dependency-aware", components: `
    - name: other
      type: webservice
      properties:
        image: ghcr.io/example/other:v1.0.0
        port: 8080
`, policies: `
  policies:
    - name: order
      type: dependency
      properties:
        rules:
          - component: other
            dependsOn: [web]
`},
}

func duplicateApp(webComponent, shapeComponents, policies string) string {
	return `apiVersion: launcher.gokure.dev/v1alpha1
kind: Application
metadata:
  name: shop
  namespace: default
spec:
  components:
` + webComponent + shapeComponents + policies
}

const webTwoConfigMaps = `    - name: web
      type: webservice
      properties:
        image: ghcr.io/example/web:v1.0.0
        port: 8080
      traits:
        - type: configmap
          properties:
            name: dup
            data:
              a: "1"
        - type: configmap
          properties:
            name: dup
            data:
              b: "2"
`

const webConfigMapAndClaim = `    - name: web
      type: webservice
      properties:
        image: ghcr.io/example/web:v1.0.0
        port: 8080
      traits:
        - type: configmap
          properties:
            name: dup
            data:
              a: "1"
        - type: pvc
          properties:
            name: dup
            size: 1Gi
`

func helmWeb(traits string) string {
	return `    - name: web
      type: helm
      properties:
        chart: web
        version: 1.0.0
        source:
          url: https://charts.example.com
        valuesMode: configMap
        values:
          replicaCount: 2
` + traits
}

func TestDuplicateTraitObjects_TwoAuthoredTraits(t *testing.T) {
	for _, shape := range duplicateShapes {
		t.Run(shape.name, func(t *testing.T) {
			_, err := collisionCheck(t, duplicateApp(webTwoConfigMaps, shape.components, shape.policies))
			want := `generated-object collision: ConfigMap "default/dup" is generated by 2 sub-applications "dup" of component "web"; rename one`
			if err == nil || !strings.Contains(err.Error(), want) {
				t.Fatalf("err = %v, want one containing %q", err, want)
			}
		})
	}
}

func TestDuplicateTraitObjects_HelmValuesAgainstAuthoredTrait(t *testing.T) {
	for _, shape := range duplicateShapes {
		t.Run(shape.name, func(t *testing.T) {
			apps, err := collisionCheck(t, duplicateApp(helmWeb(""), shape.components, shape.policies))
			if err != nil {
				t.Fatalf("baseline: %v", err)
			}
			var valuesName string
			for _, a := range apps {
				for _, p := range a.Objects {
					if p == nil {
						continue
					}
					obj := *p
					if obj.GetObjectKind().GroupVersionKind().Kind == "ConfigMap" && strings.Contains(obj.GetName(), "-values-") {
						valuesName = obj.GetName()
					}
				}
			}
			if valuesName == "" {
				t.Fatal("baseline generated no helm values ConfigMap")
			}
			traits := `      traits:
        - type: configmap
          properties:
            name: ` + valuesName + `
            data:
              a: "1"
`
			_, err = collisionCheck(t, duplicateApp(helmWeb(traits), shape.components, shape.policies))
			// The helm component's values sub-application carries the ConfigMap's name.
			want := fmt.Sprintf(`generated-object collision: ConfigMap "default/%s" is generated by 2 sub-applications %q of component "web"; rename one`,
				valuesName, valuesName)
			if err == nil || !strings.Contains(err.Error(), want) {
				t.Fatalf("err = %v, want one containing %q", err, want)
			}
		})
	}
}

func TestDuplicateTraitObjects_SameNameOtherKindAccepted(t *testing.T) {
	for _, shape := range duplicateShapes {
		t.Run(shape.name, func(t *testing.T) {
			if _, err := collisionCheck(t, duplicateApp(webConfigMapAndClaim, shape.components, shape.policies)); err != nil {
				t.Fatalf("a ConfigMap and a PersistentVolumeClaim both named dup were refused: %v", err)
			}
		})
	}
}
