package components

import (
	"maps"
	"slices"

	"github.com/go-kure/kure/pkg/kubernetes"
	"github.com/go-kure/kure/pkg/stack"
	batchv1 "k8s.io/api/batch/v1"
	corev1 "k8s.io/api/core/v1"
	"sigs.k8s.io/controller-runtime/pkg/client"

	"github.com/go-kure/launcher/pkg/errors"
	"github.com/go-kure/launcher/pkg/oam"
)

// JobHandler handles OAM job components (go-kure/launcher#344, ADR-036 L1).
//
// A job is a cronjob without a schedule: the two project the same
// batchv1.JobSpec, so everything JobSpec-level comes from the shared
// schemaJobSpec/parseJobSpec/applyJobSpec in common.go, and everything
// pod-level from the shared parsePodSpec/buildPodSpec. What is job-only is the
// `suspend` key (JobSpec.Suspend, a different API field from the CronJobSpec
// Suspend the cronjob component publishes under the same name — see
// JobSpecConfig) and the two selector properties this component refuses.
type JobHandler struct{}

// CanHandle returns true for the job component type.
func (h *JobHandler) CanHandle(componentType string) bool {
	return componentType == "job"
}

// jobSpecRejectedKeys are properties an author may not set on a job component;
// each maps to the error explaining why. They are refused rather than left
// undeclared because leaving a key undeclared refuses nothing: validateProperties
// runs on EMITTED elements only, never on authored documents
// (property_validate.go's scope note), so an authored key this handler does not
// read is silently dropped rather than rejected. The message then says what to do
// instead of only naming the key.
//
// Two groups: batchv1.JobSpec fields this component does not accept, and the
// CronJobSpec-only keys that a cronjob document retyped to `job` would carry.
var jobSpecRejectedKeys = map[string]string{
	"selector":       "selector: not authorable; the Job selector is generated by the job controller from a unique per-job label, and a hand-written one silently adopts another job's pods",
	"manualSelector": "manualSelector: not authorable; it only has meaning alongside a hand-written selector, which this component does not accept",
	"template":       "template: not authorable as a whole; the pod template is projected from the component's own container and pod-level properties",
	"podFailurePolicy": "podFailurePolicy: not yet supported on this component; it is owned by go-kure/launcher#345 and refused here rather than accepted and dropped, " +
		"so a document authoring it fails loudly instead of building a Job that silently ignores its failure handling",
	// The CronJobSpec-only keys. A job component and a cronjob component differ
	// by exactly these six properties, so retyping a cronjob document to `job`
	// leaves every one of them behind — and each would be dropped in silence,
	// turning a schedule into a Job that runs once, immediately, at apply time.
	// That is the worst shape this class of defect takes: not a missing field,
	// but work executed at a time nobody asked for.
	"schedule":                   "schedule: not a job property; a job runs once when applied. Use a cronjob component to run on a schedule — a job document that still carries a schedule would otherwise run immediately, which is not what the schedule asked for",
	"timeZone":                   "timeZone: not a job property; it qualifies a cronjob's schedule, and a job has none",
	"concurrencyPolicy":          "concurrencyPolicy: not a job property; it governs overlapping runs of a cronjob's schedule, and a job runs once",
	"startingDeadlineSeconds":    "startingDeadlineSeconds: not a job property; it bounds how late a cronjob may start a missed scheduled run. For a job's own runtime bound, use activeDeadlineSeconds",
	"successfulJobsHistoryLimit": "successfulJobsHistoryLimit: not a job property; it retains past runs of a cronjob. To have a finished job clean itself up, use ttlSecondsAfterFinished",
	"failedJobsHistoryLimit":     "failedJobsHistoryLimit: not a job property; it retains past runs of a cronjob. To have a finished job clean itself up, use ttlSecondsAfterFinished",
}

// PropertySchema declares the job component's user-facing properties.
//
// batchv1.JobSpec.PodFailurePolicy is deliberately not published here: it is
// owned by go-kure/launcher#345. Absence from the schema is not what refuses it —
// jobSpecRejectedKeys above is; see the note there.
func (h *JobHandler) PropertySchema() map[string]oam.PropertySchema {
	m := map[string]oam.PropertySchema{
		"image":           {Type: oam.PropertyTypeString, Required: true, Description: "Container image reference for the job container."},
		"restartPolicy":   {Type: oam.PropertyTypeString, Default: "OnFailure", Enum: []any{"Never", "OnFailure"}, Description: "Pod restart policy for the job's containers. The Job API rejects \"Always\"."},
		"suspend":         schemaJobSuspend(),
		"env":             schemaEnv(false),
		"envFrom":         schemaEnvFrom(false),
		"resources":       schemaResources(false),
		"command":         schemaStringArray(),
		"args":            schemaStringArray(),
		"probes":          schemaProbes(false),
		"lifecycle":       schemaLifecycle(false),
		"securityContext": schemaSecurityContext(false),
		"workingDir":      schemaWorkingDir(false),
		"volumes":         schemaVolumes(),
		"initContainers":  schemaContainers(),
	}
	maps.Copy(m, schemaJobSpec(false))
	maps.Copy(m, schemaPodSpec(false, true))
	return m
}

// ToApplicationConfig converts an OAM job component to a JobConfig.
func (h *JobHandler) ToApplicationConfig(component *oam.Component, namespace string) (stack.ApplicationConfig, error) {
	config := &JobConfig{
		Name:      component.Name,
		Namespace: namespace,
	}

	props := component.Properties

	// Refused before anything is read out of props, so an author who wrote both
	// a selector and something invalid sees the selector message: the selector
	// is the one that cannot be fixed by editing a value.
	rejected := slices.Sorted(maps.Keys(jobSpecRejectedKeys))
	for _, key := range rejected {
		if _, present := props[key]; present {
			return nil, errors.New(jobSpecRejectedKeys[key])
		}
	}

	image, ok := props["image"].(string)
	if !ok {
		return nil, errors.New("required property 'image' missing or not a string")
	}
	if err := ValidateImageRef(image); err != nil {
		return nil, err
	}
	config.Image = image

	config.RestartPolicy = corev1.RestartPolicyOnFailure
	// Read raw for the same reason managedBy is, and not through
	// parseStringField: a bare `props[k].(string)` assertion makes a mistyped
	// value indistinguishable from an absent key, so `restartPolicy: 3` would
	// silently build the OnFailure default instead of being refused — but
	// parseStringField reports an authored "" as absent, and "" is a value the
	// switch below must reject rather than default. Reading raw refuses both.
	if raw, present := props["restartPolicy"]; present && !isExplicitNull(raw) {
		rp, ok := raw.(string)
		if !ok {
			return nil, errors.Errorf("restartPolicy: must be a string, got %T", raw)
		}
		switch rp {
		case string(corev1.RestartPolicyNever):
			config.RestartPolicy = corev1.RestartPolicyNever
		case string(corev1.RestartPolicyOnFailure):
			config.RestartPolicy = corev1.RestartPolicyOnFailure
		default:
			return nil, errors.Errorf("invalid restartPolicy %q, must be 'Never' or 'OnFailure'", rp)
		}
	}

	// An explicit null reads as omission here too — parseBoolField has no
	// optional* wrapper, so the check is inline rather than in common.go; adding
	// one for a single call site would be the wider migration
	// go-kure/launcher#394 owns, not this component's to start.
	if raw, present := props["suspend"]; present && !isExplicitNull(raw) {
		suspend, err := parseBoolField(props, "suspend", "suspend")
		if err != nil {
			return nil, err
		}
		config.Suspend = suspend
	}

	jobSpec, err := parseJobSpec(props)
	if err != nil {
		return nil, err
	}
	config.JobSpec = jobSpec

	env, err := parseEnv(props)
	if err != nil {
		return nil, err
	}
	config.Env = env
	envFrom, err := parseEnvFrom(props)
	if err != nil {
		return nil, err
	}
	config.EnvFrom = envFrom
	if resources, ok := props["resources"].(map[string]any); ok {
		r, err := parseResources(resources)
		if err != nil {
			return nil, errors.Wrap(err, "invalid resources configuration")
		}
		config.Resources = r
	}
	config.Command = parseCommand(props)
	config.Args = parseArgs(props)
	// namedPortsAllowed=false for the same reason as cronjob: the job component
	// exposes no port property, so its main container never declares a
	// ContainerPort for the kubelet to resolve a named probe/lifecycle port
	// against.
	probes, err := parseProbes(props, false, "")
	if err != nil {
		return nil, errors.Wrap(err, "invalid probe configuration")
	}
	config.Probes = probes
	lifecycle, err := parseLifecycle(props, false, "")
	if err != nil {
		return nil, errors.Wrap(err, "invalid lifecycle configuration")
	}
	config.Lifecycle = lifecycle
	securityContext, err := parseSecurityContext(props)
	if err != nil {
		return nil, errors.Wrap(err, "invalid securityContext configuration")
	}
	config.SecurityContext = securityContext
	if workingDir, present, err := parseStringField(props, "workingDir", "workingDir"); err != nil {
		return nil, err
	} else if present {
		config.WorkingDir = workingDir
	}

	parsed, err := parseVolumes(props)
	if err != nil {
		return nil, err
	}
	config.Volumes = parsed.Volumes
	config.VolumeMounts = parsed.Mounts
	config.PVCs = parsed.PVCs

	initContainers, err := parseInitContainers(props)
	if err != nil {
		return nil, err
	}
	config.InitContainers = initContainers

	podSpec, err := parsePodSpec(props, true)
	if err != nil {
		return nil, err
	}
	config.PodSpec = podSpec

	return config, nil
}

// JobConfig implements stack.ApplicationConfig for job components.
type JobConfig struct {
	Name          string
	Namespace     string
	Image         string
	RestartPolicy corev1.RestartPolicy
	// Suspend is batchv1.JobSpec.Suspend, presence-gated for the same reason as
	// cronjob's own pointers: the field is `omitempty`, but that only suppresses
	// a nil pointer, so writing an unconditional *bool would add `suspend: false`
	// to every generated Job that no author asked for.
	Suspend         *bool
	JobSpec         JobSpecConfig
	Env             []corev1.EnvVar
	EnvFrom         []corev1.EnvFromSource
	Resources       ResourceRequirements
	Command         []string
	Args            []string
	Probes          ProbeConfig
	Lifecycle       *corev1.Lifecycle
	SecurityContext *corev1.SecurityContext
	WorkingDir      string
	Volumes         []corev1.Volume
	VolumeMounts    []corev1.VolumeMount
	InitContainers  []InitContainerConfig
	PVCs            []PVCConfig
	// PodSpec holds the shared pod-level properties (see parsePodSpec). Parsed
	// with jobPods=true, so `podActiveDeadlineSeconds` (the pod's own deadline)
	// is accepted alongside the job-level `activeDeadlineSeconds` from
	// schemaJobSpec — two different fields, two different keys.
	PodSpec PodSpecConfig
}

// EmitsAutoHealthCheck vetoes the auto health check for the two documents that
// instruct the job not to run, the same shape as deployment's veto for
// `paused: true`: waiting on such a workload is not a health signal but a
// guaranteed timeout. A job that does run reaches Complete or Failed, which is
// what makes the check meaningful — see componentHealthCheckGVK's note in
// transform.go.
//
// The two cases are not one. `suspend: true` is the explicit one: the controller
// creates no pods at all (batchv1 JobSpec.Suspend's field doc), and suspending
// also resets the ActiveDeadlineSeconds timer, so a suspended job cannot fail by
// deadline either — the veto is unconditional.
//
// `parallelism: 0` reaches the same place by a different route: it is the
// "maximum desired number of pods the job should run at any given time", so zero
// pods run, no completion accrues, and Complete is unreachable. The difference
// is that such a job is *active*, so the ActiveDeadlineSeconds timer does run
// (the field doc measures it "relative to the startTime ... continuously
// active", and only suspension stops it). With a deadline authored, the job does
// reach Failed and the health check reports a real — if slow — result, so the
// veto is conditional on there being no deadline to fail against.
func (c *JobConfig) EmitsAutoHealthCheck() bool {
	if c.Suspend != nil && *c.Suspend {
		return false
	}
	if c.JobSpec.Parallelism != nil && *c.JobSpec.Parallelism == 0 && c.JobSpec.ActiveDeadlineSeconds == nil {
		return false
	}
	return true
}

// ServiceAccountName implements oam.ServiceAccountNamer: the authored
// serviceAccountName, else the per-component ServiceAccount named after the
// component.
func (c *JobConfig) ServiceAccountName() string {
	return effectiveServiceAccountName(c.PodSpec, c.Name)
}

// ApplyPolicy applies defaults then enforces limits from the policy. A Job has
// no replicas, so — as for cronjob — only the resource, registry and pod-level
// limits apply.
func (c *JobConfig) ApplyPolicy(p oam.Policy) error {
	if p == nil {
		return nil
	}

	if err := applyDefaultQuantity(&c.Resources.Requests, corev1.ResourceCPU, p.DefaultCPURequest()); err != nil {
		return err
	}
	if err := applyDefaultQuantity(&c.Resources.Requests, corev1.ResourceMemory, p.DefaultMemoryRequest()); err != nil {
		return err
	}
	if err := applyDefaultQuantity(&c.Resources.Limits, corev1.ResourceCPU, p.DefaultCPULimit()); err != nil {
		return err
	}
	if err := applyDefaultQuantity(&c.Resources.Limits, corev1.ResourceMemory, p.DefaultMemoryLimit()); err != nil {
		return err
	}

	if err := enforceMaxResources(c.Resources, p.MaxCPU(), p.MaxMemory()); err != nil {
		return err
	}
	if err := enforceAllowedRegistries(c.Image, p.AllowedRegistries()); err != nil {
		return err
	}
	if err := enforcePrivileged(c.SecurityContext, p.AllowPrivileged()); err != nil {
		return err
	}
	if err := enforceHostPathVolumes(c.Volumes, p.AllowHostPathVolumes()); err != nil {
		return err
	}
	if err := enforceHostNamespaces(c.PodSpec, p); err != nil {
		return err
	}
	if err := enforcePodResources(c.PodSpec, p.MaxCPU(), p.MaxMemory()); err != nil {
		return err
	}
	if err := enforcePodHostProcess(c.PodSpec, p.AllowPrivileged()); err != nil {
		return err
	}
	if err := enforceContainerCapabilities(c.SecurityContext, p.AllowedContainerCapabilities(), p.ForbiddenContainerCapabilities()); err != nil {
		return err
	}
	for i, ic := range c.InitContainers {
		if err := enforceExtraContainer("initContainers", i, ic.Name, ic.Image,
			ic.Resources, ic.SecurityContext, p); err != nil {
			return err
		}
	}
	for _, pvc := range c.PVCs {
		if err := enforceMaxStorageSize(pvc.Size, p.MaxStorageSize()); err != nil {
			return err
		}
	}

	return nil
}

// Generate creates a Kubernetes Job, ServiceAccount, and any declared PVCs.
// The ServiceAccount is omitted when serviceAccountName was authored.
func (c *JobConfig) Generate(app *stack.Application) ([]*client.Object, error) {
	var err error
	c.PVCs, err = qualifyPVCNames(c.Volumes, c.PVCs, app.Name)
	if err != nil {
		return nil, err
	}
	job, err := c.createJob(app)
	if err != nil {
		return nil, err
	}

	obj := client.Object(job)
	objects := []*client.Object{&obj}
	if generatesServiceAccount(c.PodSpec) {
		saObj := client.Object(createServiceAccount(generationServiceAccountName(c, app.Name), app.Namespace, appLabels(app.Name)))
		objects = append(objects, &saObj)
	}

	for _, pvc := range c.PVCs {
		p, err := BuildPVC(pvc, app.Namespace, appLabels(app.Name))
		if err != nil {
			return nil, err
		}
		pObj := client.Object(p)
		objects = append(objects, &pObj)
	}

	return objects, nil
}

func (c *JobConfig) createJob(app *stack.Application) (*batchv1.Job, error) {
	// No Ports: the job component exposes no port property (see parseProbes'
	// namedPortsAllowed=false above).
	container := buildMainContainer(app.Name, mainContainerInput{
		Image:           c.Image,
		Command:         c.Command,
		Args:            c.Args,
		Resources:       c.Resources,
		Env:             c.Env,
		EnvFrom:         c.EnvFrom,
		Probes:          c.Probes,
		WorkingDir:      c.WorkingDir,
		Lifecycle:       c.Lifecycle,
		SecurityContext: c.SecurityContext,
		VolumeMounts:    c.VolumeMounts,
	})

	job := kubernetes.CreateJob(app.Name, app.Namespace)
	// CreateJob stamps `app: <name>` as both labels and annotations; the
	// annotation is dropped here for the same reason the other kinds drop it —
	// it duplicates the label and no consumer reads it. Spec.Selector is left
	// as CreateJob leaves it, unset: the job controller generates the selector
	// from its own unique label, which is why `selector` is refused above.
	job.Labels = appLabels(app.Name)
	job.Annotations = nil
	job.Spec.Template.Labels = appLabels(app.Name)
	if c.Suspend != nil {
		job.Spec.Suspend = copyPtr(c.Suspend)
	}
	applyJobSpec(&job.Spec, c.JobSpec)

	// Replaces the whole pod spec. c.RestartPolicy is always set (default
	// OnFailure), so the authored/defaulted value lands on the template — the
	// Job API rejects the Always that pod defaulting would otherwise apply.
	podSpec, err := buildPodSpec(podSpecInput{
		Config:                    c.PodSpec,
		DefaultServiceAccountName: generationServiceAccountName(c, app.Name),
		MainContainer:             container,
		InitContainers:            c.InitContainers,
		Volumes:                   c.Volumes,
		RestartPolicy:             c.RestartPolicy,
	})
	if err != nil {
		return nil, err
	}
	job.Spec.Template.Spec = podSpec

	return job, nil
}
