name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write
  actions: write

jobs:
  release:
    uses: go-kure/.github/.github/workflows/release.yml@main
    with:
      go_module: github.com/go-kure/launcher
    secrets: inherit
